### ISSUE TITLE
Bot should have a .desktoy (.dtoy) and a battlestation (.bst) command.

### ISSUE THREAD

**Issue by vuksavic** [6c37/deskbot#24]
.dtoy -add generic_anime_name Figma
.bst -add https://link.to/battlestation.flac

When you think about it, battlestations are a variant of ricing too.

**Comment by skewerr** [comment]
There is already a battlestation command(`.station`|`.battlestation`). Check .help station to see howit works and its aliases. Since `.station` is a urldb command and therefore stores a number of urls(5), people are welcome to add pictures of their figmas or whatever they please.

I don't think yet another command should be added for .dtoy, but I'm going to start working on a module that could provide that kind of command syntax. It's intended for `.links`.
